Django/chirp/chirp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('posts.urls'))
]

Django/chirp/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('make_post/', views.make_post, name="make_post")
]

Django/chirp/users/urls.py
from django.urls import path
from . import views 

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
]

Django/chirp/posts/models.py
from django.db import models

# Create your models here.

class User_Info(models.Model):
    user_name = models.CharField(max_length=24)
    user_image = models.URLField()
    user_bio = models.CharField(max_length=300)

    def __str__(self):
        return self.user_name

class Post(models.Model):
    content = models.TextField(max_length=128)
    date_time = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User_Info, on_delete=models.CASCADE, related_name='user')

    def __str__(self):
        post_name = f"{self.user} on {self.date_time}"
        return post_name

Django/chirp/users/models.py
from django.db import models

# Create your models here.

Django/chirp/posts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate
from .models import User_Info, Post

def index(request):
    if request.user.is_authenticated:
        return redirect('posts:home')
    else:
        return render(request, 'posts/index.html')

def home(request):
    posts = Post.objects.all()
    context = {
        "posts": posts
    }
    return render(request, 'posts/home.html', context)

def make_post(request):
    if request.method == 'POST':
        content = request.POST.get("content")
        user = request.user.username
        user = User_Info.objects.filter(user_name=user).get()
        Post.objects.create(content=content, user=user)
    return redirect('posts:home')
    

Django/chirp/users/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from posts.models import User_Info
# Create your views here.

def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password_one = request.POST.get('password1')
        password_two = request.POST.get('password2')

        if password_one == password_two:
            user = User.objects.create_user(
                password = password_one,
                username = username 
            )
            User_Info.objects.create(user_name = username)
            return redirect('posts:index')
        else:
            return redirect('posts:home')
            
    return render(request, 'users/register.html')

def login_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        print(user)
        if user is not None:
            login(request, user)
            return redirect('posts:index')

    return render(request, 'users/login.html')

def logout_user(request):
    logout(request)
    return redirect('posts:index')

Django/chirp/posts/templates/posts/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <title>Chirp you little bird, Chirp</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'posts:index' %}">Chiiiiiirp</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
            <p class='nav-link active'>Welcome, {{ user.username }}</p>
            <a class="btn btn-primary" aria-current="page" href="{% url 'users:logout' %}">Logout</a>
            </div>
          </div>
        </div>
      </nav>

      {% block content %}
      {% endblock %}



      
    </body>
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top bg-dark">
      <div class="col-md-4 d-flex align-items-center">
        <span class="text-muted">&copy; 2021 Chirp, Inc</span>
      </div>
      

    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
</html>

Django/chirp/posts/templates/posts/home.html
{% extends 'posts/base.html' %}
{% load static %}

{% block content %}

<h1 class="text-center">Chirp, Chirp Birdie</h1>
<article class='container'>
  <div class="row">
    <div class="col-md-3" style="position:fixed">
      <p>Put USER PROFILE HERE</p>
    </div>
    <div class="col-md-9 container">
      <div class="row">
        <div class="col-9">
        <form action="{% url 'posts:make_post' %}" method="POST">
          {% csrf_token %}
          <label for="content">New Post</label>
          <textarea class="form-control m-3" type="text" id="content" name="content" style="height: 100px"></textarea>
        </div>
        <div class="col-3">
          <button class='btn btn-success d-flex justify-content-center align-items-center' type="submit">Post</button>
        </div>
        </form>
      </div>
      <ul>
        {% for post in posts %}
        <li class="border border-dark row">
        <div class="col-3">
          {{ post.user.user_image }}
        </div>
        <div class="col-9">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">{{ post.user.user_name }}</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td scope="row">{{ post.content }}</th>

              </tr>
              <tr>
                <td scope="row">{{ post.date_time }}</th>
              </tr>
            </tbody>
          </table>



        </div>

        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</article>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
</body>

{% endblock %}

Django/chirp/posts/templates/posts/index.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/posts/style.css' %}">
    <title>Chirp baby, chirp</title>
</head>
<body>
    <article>
        <div class="row">
            <div class="col-sm-6">
                <img src="{% static '/posts/bird.jpg' %}" class="w-100" alt="Bird singing">
            </div>
            <div class="col-sm-6 ">
                <h1 class='text-center m-4'>Welcome to Chirp</h1>
                    <div class="row h-50 d-flex justify-content-center align-items-center">
                        <div class="col-12 d-grid gap-2 m-2">
                            <a class="btn btn-primary btn-lg" href="{% url 'users:login' %}">Login</a>
                        </div>
                        <div class="col-12 d-grid gap-2 m-2">
                            <a class="btn btn-outline-secondary btn-lg" type="button" href="{% url 'users:register' %}">Register</a>
                        </div>
                    </div>
            </div>
        </div>
    </article>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
        crossorigin="anonymous"></script>
</body>

</html>