Django/library_project/library/urls.py
from django.urls import path
from . import views 

app_name = 'library'

urlpatterns = [
    path('', views.index, name="index"),
    path('status/', views.status, name="status"),
    path('checkout/', views.checkout, name="checkout"),
    path('checkin/', views.checkin, name="checkin")
]

Django/library_project/library_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls')),
    path('', include('django.contrib.auth.urls')),
]

Django/library_project/library/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Checkout(models.Model):
    book_title = models.CharField(max_length=100)
    user = models.CharField(max_length=100)
    checkout = models.BooleanField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.book_title

class Genre(models.Model):
    genre_name = models.CharField(max_length=100)

    def __str__(self):
        return self.genre_name

class Book(models.Model):
    title = models.CharField(max_length=100)
    publish_date = models.DateField()
    author = models.ForeignKey(Author, on_delete=models.PROTECT, related_name='book')
    image = models.URLField()
    checked_out = models.BooleanField()
    genre = models.ManyToManyField(Genre)

    def __str__(self):
        return self.title

Django/library_project/library/views.py
from django.shortcuts import render
from .models import Book, Author, Checkout, Genre

def index(request):
    books = Book.objects.all()
    authors = Author.objects.all()
    context = {
        'books': books,
        'author': authors,
    }
    return render(request, 'library/index.html', context)

def checkout(request):
    books = Book.objects.all()
    if request.method == 'POST':
        user = request.POST.get("user")
        book = request.POST.get("name")
        print('Book Title: ' + book)
        checkout = True
        Checkout.objects.create(checkout=checkout, book_title=book, user=user)
        book_edit = books.get(title=book)
        book_edit.checked_out = checkout
        book_edit.save()
    return index(request)

def checkin(request):
    books = Book.objects.all()
    if request.method == 'POST':
        book = request.POST.get("name")
        
        filtered_book = Checkout.objects.filter(book_title=book, checkout=True).order_by('-timestamp').first()
        user = filtered_book.user
        checkout = False
        Checkout.objects.create(checkout=checkout, book_title=book, user=user)
        book_edit = books.get(title=book)
        book_edit.checked_out = checkout
        book_edit.save()
    return index(request)

def status(request):
    checkouts = Checkout.objects.all()
    context = {
        'checkouts': checkouts
    }
    return render(request, 'library/status.html', context)

Django/library_project/library/templates/library/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="{% static 'library/style.css' %}">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>

<body>
    <header>
        <nav>
            <div class="nav-wrapper">
              <a href="{% url 'library:index' %}" class="brand-logo m-1">The Library</a>
              <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a class="m-1" href="{% url 'library:index' %}#books">Books</a></li>
              </ul>
            </div>
          </nav>
          
    </header>

    {% block content %}
    {% endblock %}

    <footer class="page-footer">
        <div class="footer-copyright">
            <div class="container">
                © 2021 Copyright
            </div>
        </div>
    </footer>
    <!--JavaScript at end of body for optimized loading-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>

</html>

Django/library_project/library/templates/library/index.html
{% extends 'library/base.html' %}

{% block content %}

<main>
    <article>
        <div class="row" id="books">
            {% for book in books %}
            <div class="col m4">
                <div class="card">
                    <div class="card-image">
                        <img src="{{ book.image }}" alt="">
                    </div>
                    <div class="card-content">

                        <span class="card-title">{{ book.title }}</span>
                        <p>Author: {{ book.author.name }}</p>
                        <p>Publish Date: {{ book.publish_date }}</p>
                        <p>Genre: {% for each_genre in book.genre.all %}
                            {{ each_genre }} |
                            {% endfor %}
                        </p>
                    </div>
                    <div class="card-action">
                        {% if book.checked_out == True %}
                        <form action="{% url 'library:checkin' %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="waves-effect waves-light btn-large" value="{{ book.title }}"
                                name="name">Check in Book</a>
                        </form>
                        {% else %}
                        <form action="{% url 'library:checkout' %}" method="POST">
                            {% csrf_token %}
                            <div class="row">
                                <div class="input-field col s6">
                                    <input value="" name="user" id="user" type="text">
                                    <label class="active" for="user">Username</label>
                                </div>
                            </div>
                            <button type="submit" class="waves-effect waves-light btn-large" value="{{ book.title }}"
                                name="name">Check out Book</a>
                        </form>
                        {% endif %}
                    </div>
                    <div class="card-action">

                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </article>
    <article>
        <div class="row">
            <a href="{% url 'library:status' %}" class="waves-effect waves-light btn center-align">Library Status
                Page</a>
        </div>
    </article>
</main>
{% endblock %}

Django/library_project/library/templates/library/status.html
{% extends 'library/base.html' %}

{% block content %}
<div class="m-1">
<h2 class="center-align">Check In and Check Out History</h2>
<table >
    <thead>
      <tr>
          <th>Book</th>
          <th>User</th>
          <th>Checkout</th>
          <th>Transaction Time</th>
      </tr>
    </thead>

    <tbody>
    {% for checkout in checkouts %}
      <tr>
        <td>{{ checkout.book_title }}</td>
        <td>{{ checkout.user }}</td>
        <td>{{ checkout.checkout }}</td>
        <td>{{ checkout.timestamp }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}